# no tests yet
stages:
  - test
  - build

tests:
  image: python:latest
  stage: test
  tags:
    - docker
    - owned
  script:
    - python test_filecense.py

container:
  image: docker:latest
  stage: build
  tags:
    - docker
    - owned
  script:
    - docker build --tag $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME .
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME
  only:
    refs:
      - branches
    changes:
      - filecense.py
      - Dockerfile
      - .gitlab-ci.yml
